sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: dandan
  wechat:
    appid: wx0083d96b283bf483
    secret: 4a2ebe8fab4c7e94da85d9b901f40efb
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com # 对应公网endpoint地址
      keyid: LTAI5tNzUMXZ9jfLHqS79pxH
      keysecret: 4oweZXHD1bu67tZsn2roj8gZWRpb3Q
      bucketname: dd-mail  #可以代码层面实现
redis:
  host: 192.168.183.130
  port: 6379